### ISSUE TITLE
tidyTime doesn't handle my timezone (east of GMT)

### ISSUE THREAD

**Issue by gspringtech** [devfacet/utilex#1]
tidyDate calls pDate.getTimezoneOffset() - which returns -570 (Adelaide, Australia)
After manipulation, you end up with a string like 
'2014-05-28T04:25:30.640+0-9.5:00' instead of
'2014-05-28T04:25:30.640-09:30'

Two things wrong - first the negative offset, and second, the half-hour.
(edited - removed my awful function)

Perhaps this is better:
return new Date(d.getTime() - (d.getTimezoneOffset() \* 60 \* 1000)).toISOString().replace("T"," ").substring(0,19);

**Comment by cmfatih** [comment]
`tidyTime` is removed by v3.
